from schemas.categoria_cardapio import CategoriaCardapioSchema, ListagemCategoriasCardapioSchema, ListagemCategoriaCardapioComItensSchema, apresenta_categorias_cardapio, apresenta_categorias_cardapio_com_itens
from schemas.item_cardapio import ItemCardapioSchema,  ItemCardapioDelSchema, ItemCardapioViewSchema, ItemCardapioBuscaSchema, ItemCardapioAddSchema, apresenta_novo_item_cardapio
from schemas.loja import LojaSchema, LojaViewSchema, ListagemLoja, apresenta_lojas
from schemas.fidelidade import FidelidadeSchema, FidelidadeViewSchema, FidelidadeAddSchema, apresenta_novo_fidelidade
from schemas.fale_conosco import FaleConoscoSchema, FaleConoscoViewSchema, FaleConoscoAddSchema, ListagemFaleConosco, apresenta_faleconosco, apresenta_novo_fale_conosco
from schemas.reserva import ReservaSchema, ReservaViewSchema, ReservaAddSchema, apresenta_nova_reserva, ListagemReserva, apresenta_reserva
from schemas.error import ErrorSchema